name: light_quiz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter_bloc:
  modal_progress_hud_nsn: ^0.5.1
  top_snackbar_flutter: ^3.2.0
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  dartz: ^0.10.1
  dio:
  jwt_decoder: ^2.0.1
  water_drop_nav_bar: ^2.2.2
  lottie:
  icons_launcher:
  cached_network_image: ^3.4.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
