// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjzlMg961DnFCDYGinHVtnwlhe6-14KVg',
    appId: '1:948166851538:web:ecb03f5a6880ab7862e60b',
    messagingSenderId: '948166851538',
    projectId: 'light-quiz-2f9ef',
    authDomain: 'light-quiz-2f9ef.firebaseapp.com',
    storageBucket: 'light-quiz-2f9ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVPNjBCgm-cku-C2I_0iMoAqcru2TxOk',
    appId: '1:948166851538:android:e907fad4eae8731862e60b',
    messagingSenderId: '948166851538',
    projectId: 'light-quiz-2f9ef',
    storageBucket: 'light-quiz-2f9ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARWs9KCAHFrnDn09UuDB3HfeqtqIRKTR4',
    appId: '1:948166851538:ios:3c6d25fc1b19033f62e60b',
    messagingSenderId: '948166851538',
    projectId: 'light-quiz-2f9ef',
    storageBucket: 'light-quiz-2f9ef.firebasestorage.app',
    iosBundleId: 'com.example.lightQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARWs9KCAHFrnDn09UuDB3HfeqtqIRKTR4',
    appId: '1:948166851538:ios:3c6d25fc1b19033f62e60b',
    messagingSenderId: '948166851538',
    projectId: 'light-quiz-2f9ef',
    storageBucket: 'light-quiz-2f9ef.firebasestorage.app',
    iosBundleId: 'com.example.lightQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjzlMg961DnFCDYGinHVtnwlhe6-14KVg',
    appId: '1:948166851538:web:cf2591f6834c267e62e60b',
    messagingSenderId: '948166851538',
    projectId: 'light-quiz-2f9ef',
    authDomain: 'light-quiz-2f9ef.firebaseapp.com',
    storageBucket: 'light-quiz-2f9ef.firebasestorage.app',
  );
}
